/*
  # Add AI-generated summary field to feedback items

  1. Changes
    - Add `summary` column to `feedback_items` table
      - `summary` (text) - Brief AI-generated summary of the content
      - This will store concise, informative summaries of articles

  2. Notes
    - Summary will be generated by AI and stored for quick display
    - Helps users understand content at a glance without reading full text
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'feedback_items' AND column_name = 'summary'
  ) THEN
    ALTER TABLE feedback_items ADD COLUMN summary text;
  END IF;
END $$;
